language: node_js
node_js:
- '6'
script:
- npm start &
- npm test
deploy:
  provider: heroku
  api_key:
    secure: VMY9PMjD0foxRk1ADAT+pEndIsqSwDxv2tccW52rs4+Hs4g6Jjg6nG0gawipTGo8aXdCzCux4avhmZ2iHdDuvamEBUHpLt5yMMwsMGqqW0cmkHrOxccltJSJDUQ4aJGBcPp9VlbNzFUX65UyvXyvOfFFSZSxr4lhi7KjS0ORQSIk05AciRXt5F/7a9t94Cz2LFh9tnU5x6qzChxE+rHhxNsj3OJkbaM8sxcX32xsvhvoeo9HbxQ3BZDPiExDKZLHUjsRkvZm+1N3XVOH6i+z/abfQ0ss6dqCfWktZUpnxjUaM6C6X8tZhcTP35ou7W0BTK9DZK4VdC+I8VhPbtlwGcTwvVrxkEO156Z1byKKCa8YQTSVeIEkNJ9bCLdNQb868fhVU8aghC+Zg6uhqzFyGPz5ON/38uoCny+MWxI1o6LadSAEOBkoUzu8GyS+8H52163jOeUhRnkC6KbKzmBGTEzbljVgmMJdCiFzaQD7llS+tM/JRP01sq85zm4MEoRmByHqOg26GbSQKjeOfBCM0FeDEfHGSm0eiUBTuzZftgNcJ2uOggHM40wXLx7/03lEP+0R8Tv4lZG5KfbDD9jh9wGhbSkcQR3uORlddTzHH23zt65FtpgxakKKjfCsvIZEVRYZWjPRyMSm0l5r1DrrCoUie04xYubrL+cOORtWj2c=
  app: react-ion
  on:
    repo: React-Ion/React-Ion
